version: "2"
services:
  web:
    build: .
    container_name: aws-bucketeer
    restart: always
    volumes:
      - ./:/var/www/html
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      AWSAccessKeyId: ${AWSAccessKeyId}
      AWSSecretKey: ${AWSSecretKey}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
      BLOGINFO_URL: http://localhost:${APACHE_PORT}
      BASE_URI: /
      CBLOG_ENABLED: ${CBLOG_ENABLED}
      PP_ENABLED: ${PP_ENABLED}
      SOLR_CORE: mycore
      SOLR_HOST: solr
      SOLR_PORT: 8983
      TIMEZONE: ${TIMEZONE}
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_MODE: debug
      XDEBUG_SESSION: xdebug_session_for_RST
    ports:
      - ${APACHE_PORT}:80
  solr:
    image: solr:latest
    #image: solr:8.5.1
    volumes:
      #- data:/opt/solr/server/solr/mycores
      - ./data/solr/data:/var/solr/data
    #environment:
    #SOLR_HOME: /mysolrhome
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
